language: python
sudo: required
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - source activate augur
install:
  - pip3 install -e .[dev]
script:
  - (pytest -c pytest.python3.ini)
  - (bash tests/builds/runner.sh)
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_BRANCH = "release" ]]; then
      ./devel/travis-rebuild-docker-image;
    fi
